package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dinningtable generated by hbm2java
 */
@Entity
@Table(name = "dinningtable", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "dTableName"))
public class DinningTable implements java.io.Serializable {

	private Integer dtableId;
	private Byte regionId;
	private String dtableName;
	private byte dtableState;
	private String dtableDesc;
	private String dtableRemark;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public DinningTable() {
	}

	public DinningTable(String dtableName, byte dtableState) {
		this.dtableName = dtableName;
		this.dtableState = dtableState;
	}

	public DinningTable(Byte regionId, String dtableName, byte dtableState,
			String dtableDesc, String dtableRemark, Byte delFlag,
			Date lastSubTime, Integer subBy) {
		this.regionId = regionId;
		this.dtableName = dtableName;
		this.dtableState = dtableState;
		this.dtableDesc = dtableDesc;
		this.dtableRemark = dtableRemark;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dTableID", unique = true, nullable = false)
	public Integer getDtableId() {
		return this.dtableId;
	}

	public void setDtableId(Integer dtableId) {
		this.dtableId = dtableId;
	}

	@Column(name = "regionID")
	public Byte getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Byte regionId) {
		this.regionId = regionId;
	}

	@Column(name = "dTableName", unique = true, nullable = false, length = 20)
	public String getDtableName() {
		return this.dtableName;
	}

	public void setDtableName(String dtableName) {
		this.dtableName = dtableName;
	}

	@Column(name = "dTableState", nullable = false)
	public byte getDtableState() {
		return this.dtableState;
	}

	public void setDtableState(byte dtableState) {
		this.dtableState = dtableState;
	}

	@Column(name = "dTableDesc", length = 100)
	public String getDtableDesc() {
		return this.dtableDesc;
	}

	public void setDtableDesc(String dtableDesc) {
		this.dtableDesc = dtableDesc;
	}

	@Column(name = "dTableRemark", length = 100)
	public String getDtableRemark() {
		return this.dtableRemark;
	}

	public void setDtableRemark(String dtableRemark) {
		this.dtableRemark = dtableRemark;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
