package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dishtype generated by hbm2java
 */
@Entity
@Table(name = "dishtype", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "dishTypeName"))
public class DishType implements java.io.Serializable {

	private Byte dishTypeId;
	private String dishTypeName;
	private String dishTypeDesc;
	private byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public DishType() {
	}

	public DishType(String dishTypeName, byte delFlag) {
		this.dishTypeName = dishTypeName;
		this.delFlag = delFlag;
	}

	public DishType(String dishTypeName, String dishTypeDesc, byte delFlag,
			Date lastSubTime, Integer subBy) {
		this.dishTypeName = dishTypeName;
		this.dishTypeDesc = dishTypeDesc;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dishTypeID", unique = true, nullable = false)
	public Byte getDishTypeId() {
		return this.dishTypeId;
	}

	public void setDishTypeId(Byte dishTypeId) {
		this.dishTypeId = dishTypeId;
	}

	@Column(name = "dishTypeName", unique = true, nullable = false, length = 15)
	public String getDishTypeName() {
		return this.dishTypeName;
	}

	public void setDishTypeName(String dishTypeName) {
		this.dishTypeName = dishTypeName;
	}

	@Column(name = "dishTypeDesc", length = 100)
	public String getDishTypeDesc() {
		return this.dishTypeDesc;
	}

	public void setDishTypeDesc(String dishTypeDesc) {
		this.dishTypeDesc = dishTypeDesc;
	}

	@Column(name = "delFlag", nullable = false)
	public byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
