package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dish generated by hbm2java
 */
@Entity
@Table(name = "dish", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "dishName"))
public class Dish implements java.io.Serializable {

	private Integer dishId;
	private Byte dishTypeId;
	private String dishName;
	private String dishSpeel;
	private BigDecimal dishCost;
	private String dishUnit;
	private BigDecimal dishPrice;
	private String dishDescription;
	private String dishCooking;
	private String dishImgUrl;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public Dish() {
	}

	public Dish(String dishName, BigDecimal dishCost, String dishUnit,
			BigDecimal dishPrice) {
		this.dishName = dishName;
		this.dishCost = dishCost;
		this.dishUnit = dishUnit;
		this.dishPrice = dishPrice;
	}

	public Dish(Byte dishTypeId, String dishName, String dishSpeel,
			BigDecimal dishCost, String dishUnit, BigDecimal dishPrice,
			String dishDescription, String dishCooking, String dishImgUrl,
			Byte delFlag, Date lastSubTime, Integer subBy) {
		this.dishTypeId = dishTypeId;
		this.dishName = dishName;
		this.dishSpeel = dishSpeel;
		this.dishCost = dishCost;
		this.dishUnit = dishUnit;
		this.dishPrice = dishPrice;
		this.dishDescription = dishDescription;
		this.dishCooking = dishCooking;
		this.dishImgUrl = dishImgUrl;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dishID", unique = true, nullable = false)
	public Integer getDishId() {
		return this.dishId;
	}

	public void setDishId(Integer dishId) {
		this.dishId = dishId;
	}

	@Column(name = "dishTypeID")
	public Byte getDishTypeId() {
		return this.dishTypeId;
	}

	public void setDishTypeId(Byte dishTypeId) {
		this.dishTypeId = dishTypeId;
	}

	@Column(name = "dishName", unique = true, nullable = false, length = 25)
	public String getDishName() {
		return this.dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

	@Column(name = "dishSpeel", length = 25)
	public String getDishSpeel() {
		return this.dishSpeel;
	}

	public void setDishSpeel(String dishSpeel) {
		this.dishSpeel = dishSpeel;
	}

	@Column(name = "dishCost", nullable = false, precision = 10)
	public BigDecimal getDishCost() {
		return this.dishCost;
	}

	public void setDishCost(BigDecimal dishCost) {
		this.dishCost = dishCost;
	}

	@Column(name = "dishUnit", nullable = false, length = 4)
	public String getDishUnit() {
		return this.dishUnit;
	}

	public void setDishUnit(String dishUnit) {
		this.dishUnit = dishUnit;
	}

	@Column(name = "dishPrice", nullable = false, precision = 10)
	public BigDecimal getDishPrice() {
		return this.dishPrice;
	}

	public void setDishPrice(BigDecimal dishPrice) {
		this.dishPrice = dishPrice;
	}

	@Column(name = "dishDescription", length = 100)
	public String getDishDescription() {
		return this.dishDescription;
	}

	public void setDishDescription(String dishDescription) {
		this.dishDescription = dishDescription;
	}

	@Column(name = "dishCooking", length = 10)
	public String getDishCooking() {
		return this.dishCooking;
	}

	public void setDishCooking(String dishCooking) {
		this.dishCooking = dishCooking;
	}

	@Column(name = "dishImgUrl", length = 100)
	public String getDishImgUrl() {
		return this.dishImgUrl;
	}

	public void setDishImgUrl(String dishImgUrl) {
		this.dishImgUrl = dishImgUrl;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
