package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Endcartecontent generated by hbm2java
 */
@Entity
@Table(name = "endcartecontent", catalog = "spartadinna")
public class EndCarteContent implements java.io.Serializable {

	private Integer eccid;
	private int eccdishId;
	private byte eccdishNum;
	private BigDecimal ecctotalPrice;
	private int ecceciid;
	private String eccspecilDesc;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public EndCarteContent() {
	}

	public EndCarteContent(int eccdishId, byte eccdishNum,
			BigDecimal ecctotalPrice, int ecceciid) {
		this.eccdishId = eccdishId;
		this.eccdishNum = eccdishNum;
		this.ecctotalPrice = ecctotalPrice;
		this.ecceciid = ecceciid;
	}

	public EndCarteContent(int eccdishId, byte eccdishNum,
			BigDecimal ecctotalPrice, int ecceciid, String eccspecilDesc,
			Byte delFlag, Date lastSubTime, Integer subBy) {
		this.eccdishId = eccdishId;
		this.eccdishNum = eccdishNum;
		this.ecctotalPrice = ecctotalPrice;
		this.ecceciid = ecceciid;
		this.eccspecilDesc = eccspecilDesc;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ECCID", unique = true, nullable = false)
	public Integer getEccid() {
		return this.eccid;
	}

	public void setEccid(Integer eccid) {
		this.eccid = eccid;
	}

	@Column(name = "ECCDishID", nullable = false)
	public int getEccdishId() {
		return this.eccdishId;
	}

	public void setEccdishId(int eccdishId) {
		this.eccdishId = eccdishId;
	}

	@Column(name = "ECCDishNum", nullable = false)
	public byte getEccdishNum() {
		return this.eccdishNum;
	}

	public void setEccdishNum(byte eccdishNum) {
		this.eccdishNum = eccdishNum;
	}

	@Column(name = "ECCTotalPrice", nullable = false, precision = 10)
	public BigDecimal getEcctotalPrice() {
		return this.ecctotalPrice;
	}

	public void setEcctotalPrice(BigDecimal ecctotalPrice) {
		this.ecctotalPrice = ecctotalPrice;
	}

	@Column(name = "ECCECIID", nullable = false)
	public int getEcceciid() {
		return this.ecceciid;
	}

	public void setEcceciid(int ecceciid) {
		this.ecceciid = ecceciid;
	}

	@Column(name = "ECCSpecilDesc", length = 20)
	public String getEccspecilDesc() {
		return this.eccspecilDesc;
	}

	public void setEccspecilDesc(String eccspecilDesc) {
		this.eccspecilDesc = eccspecilDesc;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
