package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Endcarteinfo generated by hbm2java
 */
@Entity
@Table(name = "endcarteinfo", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "ECISwiftNumber"))
public class EndCarteInfo implements java.io.Serializable {

	private Integer eciid;
	private String eciswiftNumber;
	private byte ecistate;
	private Integer ecidTableId;
	private Integer eciwaiterId;
	private int ecicashierId;
	private Integer ecicustomerId;
	private Integer ecimemId;
	private int ecidishNums;
	private Integer eciamountPeoplo;
	private Date ecirepastTime;
	private Date ecibillTime;
	private BigDecimal eciconsumeAmount;
	private BigDecimal ecidiscount;
	private BigDecimal ecipaidAmount;
	private byte[] eciremark;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public EndCarteInfo() {
	}

	public EndCarteInfo(String eciswiftNumber, byte ecistate, int ecicashierId,
			int ecidishNums, Date ecibillTime, BigDecimal eciconsumeAmount,
			BigDecimal ecipaidAmount) {
		this.eciswiftNumber = eciswiftNumber;
		this.ecistate = ecistate;
		this.ecicashierId = ecicashierId;
		this.ecidishNums = ecidishNums;
		this.ecibillTime = ecibillTime;
		this.eciconsumeAmount = eciconsumeAmount;
		this.ecipaidAmount = ecipaidAmount;
	}

	public EndCarteInfo(String eciswiftNumber, byte ecistate,
			Integer ecidTableId, Integer eciwaiterId, int ecicashierId,
			Integer ecicustomerId, Integer ecimemId, int ecidishNums,
			Integer eciamountPeoplo, Date ecirepastTime, Date ecibillTime,
			BigDecimal eciconsumeAmount, BigDecimal ecidiscount,
			BigDecimal ecipaidAmount, byte[] eciremark, Byte delFlag,
			Date lastSubTime, Integer subBy) {
		this.eciswiftNumber = eciswiftNumber;
		this.ecistate = ecistate;
		this.ecidTableId = ecidTableId;
		this.eciwaiterId = eciwaiterId;
		this.ecicashierId = ecicashierId;
		this.ecicustomerId = ecicustomerId;
		this.ecimemId = ecimemId;
		this.ecidishNums = ecidishNums;
		this.eciamountPeoplo = eciamountPeoplo;
		this.ecirepastTime = ecirepastTime;
		this.ecibillTime = ecibillTime;
		this.eciconsumeAmount = eciconsumeAmount;
		this.ecidiscount = ecidiscount;
		this.ecipaidAmount = ecipaidAmount;
		this.eciremark = eciremark;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ECIID", unique = true, nullable = false)
	public Integer getEciid() {
		return this.eciid;
	}

	public void setEciid(Integer eciid) {
		this.eciid = eciid;
	}

	@Column(name = "ECISwiftNumber", unique = true, nullable = false, length = 20)
	public String getEciswiftNumber() {
		return this.eciswiftNumber;
	}

	public void setEciswiftNumber(String eciswiftNumber) {
		this.eciswiftNumber = eciswiftNumber;
	}

	@Column(name = "ECIState", nullable = false)
	public byte getEcistate() {
		return this.ecistate;
	}

	public void setEcistate(byte ecistate) {
		this.ecistate = ecistate;
	}

	@Column(name = "ECIdTableID")
	public Integer getEcidTableId() {
		return this.ecidTableId;
	}

	public void setEcidTableId(Integer ecidTableId) {
		this.ecidTableId = ecidTableId;
	}

	@Column(name = "ECIWaiterID")
	public Integer getEciwaiterId() {
		return this.eciwaiterId;
	}

	public void setEciwaiterId(Integer eciwaiterId) {
		this.eciwaiterId = eciwaiterId;
	}

	@Column(name = "ECICashierID", nullable = false)
	public int getEcicashierId() {
		return this.ecicashierId;
	}

	public void setEcicashierId(int ecicashierId) {
		this.ecicashierId = ecicashierId;
	}

	@Column(name = "ECICustomerID")
	public Integer getEcicustomerId() {
		return this.ecicustomerId;
	}

	public void setEcicustomerId(Integer ecicustomerId) {
		this.ecicustomerId = ecicustomerId;
	}

	@Column(name = "ECIMemID")
	public Integer getEcimemId() {
		return this.ecimemId;
	}

	public void setEcimemId(Integer ecimemId) {
		this.ecimemId = ecimemId;
	}

	@Column(name = "ECIDishNums", nullable = false)
	public int getEcidishNums() {
		return this.ecidishNums;
	}

	public void setEcidishNums(int ecidishNums) {
		this.ecidishNums = ecidishNums;
	}

	@Column(name = "ECIAmountPeoplo")
	public Integer getEciamountPeoplo() {
		return this.eciamountPeoplo;
	}

	public void setEciamountPeoplo(Integer eciamountPeoplo) {
		this.eciamountPeoplo = eciamountPeoplo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ECIRepastTime", length = 19)
	public Date getEcirepastTime() {
		return this.ecirepastTime;
	}

	public void setEcirepastTime(Date ecirepastTime) {
		this.ecirepastTime = ecirepastTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ECIBillTime", nullable = false, length = 19)
	public Date getEcibillTime() {
		return this.ecibillTime;
	}

	public void setEcibillTime(Date ecibillTime) {
		this.ecibillTime = ecibillTime;
	}

	@Column(name = "ECIConsumeAmount", nullable = false, precision = 10)
	public BigDecimal getEciconsumeAmount() {
		return this.eciconsumeAmount;
	}

	public void setEciconsumeAmount(BigDecimal eciconsumeAmount) {
		this.eciconsumeAmount = eciconsumeAmount;
	}

	@Column(name = "ECIDiscount", precision = 4)
	public BigDecimal getEcidiscount() {
		return this.ecidiscount;
	}

	public void setEcidiscount(BigDecimal ecidiscount) {
		this.ecidiscount = ecidiscount;
	}

	@Column(name = "ECIPaidAmount", nullable = false, precision = 10)
	public BigDecimal getEcipaidAmount() {
		return this.ecipaidAmount;
	}

	public void setEcipaidAmount(BigDecimal ecipaidAmount) {
		this.ecipaidAmount = ecipaidAmount;
	}

	@Column(name = "ECIRemark")
	public byte[] getEciremark() {
		return this.eciremark;
	}

	public void setEciremark(byte[] eciremark) {
		this.eciremark = eciremark;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
