package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Membertype generated by hbm2java
 */
@Entity
@Table(name = "membertype", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "memTypeName"))
public class MemberType implements java.io.Serializable {

	private Integer memTypeId;
	private char memTypeName;
	private BigDecimal memTypeDiscount;
	private String memTypeDesc;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public MemberType() {
	}

	public MemberType(char memTypeName) {
		this.memTypeName = memTypeName;
	}

	public MemberType(char memTypeName, BigDecimal memTypeDiscount,
			String memTypeDesc, Byte delFlag, Date lastSubTime, Integer subBy) {
		this.memTypeName = memTypeName;
		this.memTypeDiscount = memTypeDiscount;
		this.memTypeDesc = memTypeDesc;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "memTypeID", unique = true, nullable = false)
	public Integer getMemTypeId() {
		return this.memTypeId;
	}

	public void setMemTypeId(Integer memTypeId) {
		this.memTypeId = memTypeId;
	}

	@Column(name = "memTypeName", unique = true, nullable = false, length = 1)
	public char getMemTypeName() {
		return this.memTypeName;
	}

	public void setMemTypeName(char memTypeName) {
		this.memTypeName = memTypeName;
	}

	@Column(name = "memTypeDiscount", precision = 4)
	public BigDecimal getMemTypeDiscount() {
		return this.memTypeDiscount;
	}

	public void setMemTypeDiscount(BigDecimal memTypeDiscount) {
		this.memTypeDiscount = memTypeDiscount;
	}

	@Column(name = "memTypeDesc", length = 100)
	public String getMemTypeDesc() {
		return this.memTypeDesc;
	}

	public void setMemTypeDesc(String memTypeDesc) {
		this.memTypeDesc = memTypeDesc;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
