package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "regionName"))
public class Region implements java.io.Serializable {

	private Byte regionId;
	private String regionName;
	private BigDecimal regionMinConsume;
	private Integer regionMaxConsumer;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public Region() {
	}

	public Region(String regionName) {
		this.regionName = regionName;
	}

	public Region(String regionName, BigDecimal regionMinConsume,
			Integer regionMaxConsumer, Byte delFlag, Date lastSubTime,
			Integer subBy) {
		this.regionName = regionName;
		this.regionMinConsume = regionMinConsume;
		this.regionMaxConsumer = regionMaxConsumer;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "regionID", unique = true, nullable = false)
	public Byte getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Byte regionId) {
		this.regionId = regionId;
	}

	@Column(name = "regionName", unique = true, nullable = false, length = 30)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Column(name = "regionMinConsume", precision = 10)
	public BigDecimal getRegionMinConsume() {
		return this.regionMinConsume;
	}

	public void setRegionMinConsume(BigDecimal regionMinConsume) {
		this.regionMinConsume = regionMinConsume;
	}

	@Column(name = "regionMaxConsumer")
	public Integer getRegionMaxConsumer() {
		return this.regionMaxConsumer;
	}

	public void setRegionMaxConsumer(Integer regionMaxConsumer) {
		this.regionMaxConsumer = regionMaxConsumer;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
