package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "roleName"))
public class Role implements java.io.Serializable {

	private Byte roleId;
	private String roleName;
	private Byte delFlag;
	private Date lastSubTime;
	private int subBy;

	public Role() {
	}

	public Role(String roleName, int subBy) {
		this.roleName = roleName;
		this.subBy = subBy;
	}

	public Role(String roleName, Byte delFlag, Date lastSubTime, int subBy) {
		this.roleName = roleName;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "roleID", unique = true, nullable = false)
	public Byte getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Byte roleId) {
		this.roleId = roleId;
	}

	@Column(name = "roleName", unique = true, nullable = false, length = 10)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy", nullable = false)
	public int getSubBy() {
		return this.subBy;
	}

	public void setSubBy(int subBy) {
		this.subBy = subBy;
	}

}
