package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tempendcartecontent generated by hbm2java
 */
@Entity
@Table(name = "tempendcartecontent", catalog = "spartadinna")
public class TempCarteContent implements java.io.Serializable {

	private Integer teccid;
	private String teciswiftNumber;
	private int teccdishId;
	private byte teccdishNum;
	private BigDecimal tecctotalPrice;
	private String teccspecilDesc;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public TempCarteContent() {
	}

	public TempCarteContent(String teciswiftNumber, int teccdishId,
			byte teccdishNum, BigDecimal tecctotalPrice) {
		this.teciswiftNumber = teciswiftNumber;
		this.teccdishId = teccdishId;
		this.teccdishNum = teccdishNum;
		this.tecctotalPrice = tecctotalPrice;
	}

	public TempCarteContent(String teciswiftNumber, int teccdishId,
			byte teccdishNum, BigDecimal tecctotalPrice, String teccspecilDesc,
			Byte delFlag, Date lastSubTime, Integer subBy) {
		this.teciswiftNumber = teciswiftNumber;
		this.teccdishId = teccdishId;
		this.teccdishNum = teccdishNum;
		this.tecctotalPrice = tecctotalPrice;
		this.teccspecilDesc = teccspecilDesc;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TECCID", unique = true, nullable = false)
	public Integer getTeccid() {
		return this.teccid;
	}

	public void setTeccid(Integer teccid) {
		this.teccid = teccid;
	}

	@Column(name = "TECISwiftNumber", nullable = false, length = 20)
	public String getTeciswiftNumber() {
		return this.teciswiftNumber;
	}

	public void setTeciswiftNumber(String teciswiftNumber) {
		this.teciswiftNumber = teciswiftNumber;
	}

	@Column(name = "TECCDishID", nullable = false)
	public int getTeccdishId() {
		return this.teccdishId;
	}

	public void setTeccdishId(int teccdishId) {
		this.teccdishId = teccdishId;
	}

	@Column(name = "TECCDishNum", nullable = false)
	public byte getTeccdishNum() {
		return this.teccdishNum;
	}

	public void setTeccdishNum(byte teccdishNum) {
		this.teccdishNum = teccdishNum;
	}

	@Column(name = "TECCTotalPrice", nullable = false, precision = 10)
	public BigDecimal getTecctotalPrice() {
		return this.tecctotalPrice;
	}

	public void setTecctotalPrice(BigDecimal tecctotalPrice) {
		this.tecctotalPrice = tecctotalPrice;
	}

	@Column(name = "TECCSpecilDesc", length = 20)
	public String getTeccspecilDesc() {
		return this.teccspecilDesc;
	}

	public void setTeccspecilDesc(String teccspecilDesc) {
		this.teccspecilDesc = teccspecilDesc;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
