package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tempendcarteinfo generated by hbm2java
 */
@Entity
@Table(name = "tempendcarteinfo", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "TECISwiftNumber"))
public class TempCarteInfo implements java.io.Serializable {

	private int teciid;
	private String teciswiftNumber;
	private byte tecistate;
	private Integer tecidTableId;
	private Integer tecicustomerId;
	private Integer tecimemId;
	private Integer teciwaiterId;
	private int tecidishNums;
	private Integer teciamountPeoplo;
	private Date tecirepastTime;
	private BigDecimal teciconsumeAmount;
	private BigDecimal tecicostAmount;
	private BigDecimal tecidiscount;
	private String teciremark;
	private Byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public TempCarteInfo() {
	}

	public TempCarteInfo(int teciid, String teciswiftNumber, byte tecistate,
			int tecidishNums, BigDecimal teciconsumeAmount,
			BigDecimal tecicostAmount) {
		this.teciid = teciid;
		this.teciswiftNumber = teciswiftNumber;
		this.tecistate = tecistate;
		this.tecidishNums = tecidishNums;
		this.teciconsumeAmount = teciconsumeAmount;
		this.tecicostAmount = tecicostAmount;
	}

	public TempCarteInfo(int teciid, String teciswiftNumber, byte tecistate,
			Integer tecidTableId, Integer tecicustomerId, Integer tecimemId,
			Integer teciwaiterId, int tecidishNums, Integer teciamountPeoplo,
			Date tecirepastTime, BigDecimal teciconsumeAmount,
			BigDecimal tecicostAmount, BigDecimal tecidiscount,
			String teciremark, Byte delFlag, Date lastSubTime, Integer subBy) {
		this.teciid = teciid;
		this.teciswiftNumber = teciswiftNumber;
		this.tecistate = tecistate;
		this.tecidTableId = tecidTableId;
		this.tecicustomerId = tecicustomerId;
		this.tecimemId = tecimemId;
		this.teciwaiterId = teciwaiterId;
		this.tecidishNums = tecidishNums;
		this.teciamountPeoplo = teciamountPeoplo;
		this.tecirepastTime = tecirepastTime;
		this.teciconsumeAmount = teciconsumeAmount;
		this.tecicostAmount = tecicostAmount;
		this.tecidiscount = tecidiscount;
		this.teciremark = teciremark;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@Column(name = "TECIID", unique = true, nullable = false)
	public int getTeciid() {
		return this.teciid;
	}

	public void setTeciid(int teciid) {
		this.teciid = teciid;
	}

	@Column(name = "TECISwiftNumber", unique = true, nullable = false, length = 20)
	public String getTeciswiftNumber() {
		return this.teciswiftNumber;
	}

	public void setTeciswiftNumber(String teciswiftNumber) {
		this.teciswiftNumber = teciswiftNumber;
	}

	@Column(name = "TECIState", nullable = false)
	public byte getTecistate() {
		return this.tecistate;
	}

	public void setTecistate(byte tecistate) {
		this.tecistate = tecistate;
	}

	@Column(name = "TECIdTableID")
	public Integer getTecidTableId() {
		return this.tecidTableId;
	}

	public void setTecidTableId(Integer tecidTableId) {
		this.tecidTableId = tecidTableId;
	}

	@Column(name = "TECICustomerID")
	public Integer getTecicustomerId() {
		return this.tecicustomerId;
	}

	public void setTecicustomerId(Integer tecicustomerId) {
		this.tecicustomerId = tecicustomerId;
	}

	@Column(name = "TECIMemID")
	public Integer getTecimemId() {
		return this.tecimemId;
	}

	public void setTecimemId(Integer tecimemId) {
		this.tecimemId = tecimemId;
	}

	@Column(name = "TECIWaiterID")
	public Integer getTeciwaiterId() {
		return this.teciwaiterId;
	}

	public void setTeciwaiterId(Integer teciwaiterId) {
		this.teciwaiterId = teciwaiterId;
	}

	@Column(name = "TECIDishNums", nullable = false)
	public int getTecidishNums() {
		return this.tecidishNums;
	}

	public void setTecidishNums(int tecidishNums) {
		this.tecidishNums = tecidishNums;
	}

	@Column(name = "TECIAmountPeoplo")
	public Integer getTeciamountPeoplo() {
		return this.teciamountPeoplo;
	}

	public void setTeciamountPeoplo(Integer teciamountPeoplo) {
		this.teciamountPeoplo = teciamountPeoplo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TECIRepastTime", length = 19)
	public Date getTecirepastTime() {
		return this.tecirepastTime;
	}

	public void setTecirepastTime(Date tecirepastTime) {
		this.tecirepastTime = tecirepastTime;
	}

	@Column(name = "TECIConsumeAmount", nullable = false, precision = 10)
	public BigDecimal getTeciconsumeAmount() {
		return this.teciconsumeAmount;
	}

	public void setTeciconsumeAmount(BigDecimal teciconsumeAmount) {
		this.teciconsumeAmount = teciconsumeAmount;
	}

	@Column(name = "TECICostAmount", nullable = false, precision = 10)
	public BigDecimal getTecicostAmount() {
		return this.tecicostAmount;
	}

	public void setTecicostAmount(BigDecimal tecicostAmount) {
		this.tecicostAmount = tecicostAmount;
	}

	@Column(name = "TECIDiscount", precision = 4)
	public BigDecimal getTecidiscount() {
		return this.tecidiscount;
	}

	public void setTecidiscount(BigDecimal tecidiscount) {
		this.tecidiscount = tecidiscount;
	}

	@Column(name = "TECIRemark", length = 100)
	public String getTeciremark() {
		return this.teciremark;
	}

	public void setTeciremark(String teciremark) {
		this.teciremark = teciremark;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
