package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Userinfo generated by hbm2java
 */
@Entity
@Table(name = "userinfo", catalog = "spartadinna", uniqueConstraints = {
		@UniqueConstraint(columnNames = "userIDCard"),
		@UniqueConstraint(columnNames = "userTel") })
public class UserInfo implements java.io.Serializable {

	private int userId;
	private byte userSex;
	private String userTel;
	private String userPhone;
	private String userIdcard;
	private String userDescription;
	private String userAddress;
	private byte delFlag;
	private Date lastSubTime;
	private Integer subBy;

	public UserInfo() {
	}

	public UserInfo(int userId, byte userSex, String userTel,
			String userIdcard, byte delFlag) {
		this.userId = userId;
		this.userSex = userSex;
		this.userTel = userTel;
		this.userIdcard = userIdcard;
		this.delFlag = delFlag;
	}

	public UserInfo(int userId, byte userSex, String userTel, String userPhone,
			String userIdcard, String userDescription, String userAddress,
			byte delFlag, Date lastSubTime, Integer subBy) {
		this.userId = userId;
		this.userSex = userSex;
		this.userTel = userTel;
		this.userPhone = userPhone;
		this.userIdcard = userIdcard;
		this.userDescription = userDescription;
		this.userAddress = userAddress;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
		this.subBy = subBy;
	}

	@Id
	@Column(name = "userID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userSex", nullable = false)
	public byte getUserSex() {
		return this.userSex;
	}

	public void setUserSex(byte userSex) {
		this.userSex = userSex;
	}

	@Column(name = "userTel", unique = true, nullable = false, length = 15)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	@Column(name = "userPhone", length = 15)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "userIDCard", unique = true, nullable = false, length = 20)
	public String getUserIdcard() {
		return this.userIdcard;
	}

	public void setUserIdcard(String userIdcard) {
		this.userIdcard = userIdcard;
	}

	@Column(name = "userDescription")
	public String getUserDescription() {
		return this.userDescription;
	}

	public void setUserDescription(String userDescription) {
		this.userDescription = userDescription;
	}

	@Column(name = "userAddress", length = 50)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "delFlag", nullable = false)
	public byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Column(name = "subBy")
	public Integer getSubBy() {
		return this.subBy;
	}

	public void setSubBy(Integer subBy) {
		this.subBy = subBy;
	}

}
