package com.sparta.dinna.entity;

// Generated 2015-8-25 18:03:24 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "spartadinna", uniqueConstraints = @UniqueConstraint(columnNames = "userName"))
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private Byte roleId;
	private String userRealName;
	private String userPassword;
	private Date lastLoginTime;
	private String lastLoginIp;
	private Byte delFlag;
	private Date lastSubTime;

	public User() {
	}

	public User(String userName, String userRealName, String userPassword) {
		this.userName = userName;
		this.userRealName = userRealName;
		this.userPassword = userPassword;
	}

	public User(String userName, Byte roleId, String userRealName,
			String userPassword, Date lastLoginTime, String lastLoginIp,
			Byte delFlag, Date lastSubTime) {
		this.userName = userName;
		this.roleId = roleId;
		this.userRealName = userRealName;
		this.userPassword = userPassword;
		this.lastLoginTime = lastLoginTime;
		this.lastLoginIp = lastLoginIp;
		this.delFlag = delFlag;
		this.lastSubTime = lastSubTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "userName", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "roleID")
	public Byte getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Byte roleId) {
		this.roleId = roleId;
	}

	@Column(name = "userRealName", nullable = false, length = 30)
	public String getUserRealName() {
		return this.userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}

	@Column(name = "userPassword", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLoginTime", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "lastLoginIp", length = 32)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Column(name = "delFlag")
	public Byte getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastSubTime", length = 19)
	public Date getLastSubTime() {
		return this.lastSubTime;
	}

	public void setLastSubTime(Date lastSubTime) {
		this.lastSubTime = lastSubTime;
	}

	@Override
	public String toString() {
		return "User [userName=" + userName + ", userRealName=" + userRealName
				+ ", userPassword=" + userPassword + "]";
	}

}
